Repository ECube-Reboot/LiveOn-Reborn-iOS, pull requests merged in 2022-09, with the labels that each got.

#57 [Feat] CalendarMain Get,Post API 연동
  liveOnReboot/.DS_Store
  liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
  liveOnReboot/liveOn/Extensions/Date+Extension.swift
  liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
  liveOnReboot/liveOn/Network/Calendar/DTO/CalendarDTO.swift
  liveOnReboot/liveOn/Network/Calendar/DTO/CalendarGiftBoxDTO.swift
  liveOnReboot/liveOn/Network/Calendar/DTO/CalendarMainDTO.swift
  liveOnReboot/liveOn/Network/Calendar/EndPoint/CalendarEndPoint.swift
  liveOnReboot/liveOn/Network/Calendar/EndPoint/CalendarGiftBoxEndPoint.swift
  liveOnReboot/liveOn/Network/Calendar/EndPoint/CalendarMainEndPoint.swift
  liveOnReboot/liveOn/Network/Calendar/Service/CalendarGiftBoxService.swift
  liveOnReboot/liveOn/Network/Calendar/Service/CalendarMainService.swift
  liveOnReboot/liveOn/Network/Calendar/Service/CalendarService.swift
  liveOnReboot/liveOn/Network/Config/APIEnvironment.swift
  liveOnReboot/liveOn/Resource/Assets.xcassets/listIcon/noteIcon.imageset/Contents.json
  liveOnReboot/liveOn/Resource/Assets.xcassets/listIcon/noteIcon.imageset/letterIcon.png
  liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
  liveOnReboot/liveOn/View/Calendar/CalendarGiftBox.swift
  liveOnReboot/liveOn/View/Calendar/CalendarView.swift
  liveOnReboot/liveOn/View/Calendar/UpcomingEventsView.swift
  liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
  liveOnReboot/liveOn/ViewModel/Calendar/CalendarViewModel.swift
  liveOnReboot/liveOn/ViewModel/Calendar/DateToStringUpcomingEventsViewModel.swift
  liveOnReboot/liveOn/ViewModel/Calendar/EventStoreViewModel.swift
  liveOnReboot/liveOnReboot.xcodeproj/project.pbxproj
  liveOnReboot/liveOnReboot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🖇 API, 🗓 Calender

#68 [Feat] Calendar Day DetailView 추가
  liveOnReboot/liveOn/Network/Calendar/DTO/CalendarDayDTO.swift
  liveOnReboot/liveOn/Network/Calendar/EndPoint/CalendarMainEndPoint.swift
  liveOnReboot/liveOn/Network/Calendar/Service/CalendarMainService.swift
  liveOnReboot/liveOn/View/Calendar/CalendarGiftBox.swift
  liveOnReboot/liveOn/View/Calendar/CalendarView.swift
  liveOnReboot/liveOn/View/Calendar/UpcomingEventsView.swift
  liveOnReboot/liveOn/ViewModel/Calendar/CalendarViewModel.swift
  liveOnReboot/liveOnReboot.xcodeproj/project.pbxproj
Labels: 🖇 API, 🗓 Calender

#67 [Feat] FetchMemberProfile 구현
  liveOnReboot/liveOn/Extensions/Date+Extension.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigDTO.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigEndPoint.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigService.swift
  liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
  liveOnReboot/liveOnReboot.xcodeproj/project.pbxproj
Labels: 🖇 API

#62 [FEAT] 음성메시지 API 함수들 완료
  liveOnReboot/liveOn/Model/Gift/VoiceMail/Voicemail.swift
  liveOnReboot/liveOn/Network/Gift/VoiceMail/DTO/VoiceMailDTO.swift
  liveOnReboot/liveOn/Network/Gift/VoiceMail/EndPoint/VoiceMailEndPoint.swift
  liveOnReboot/liveOn/Network/Gift/VoiceMail/Service/VoiceMailService.swift
  liveOnReboot/liveOn/View/CommonComponents/LoadingView.swift
  liveOnReboot/liveOn/View/Gift/VoiceMail/CreateVoicemailView.swift
  liveOnReboot/liveOn/View/Gift/VoiceMail/SingleVoicemailView.swift
  liveOnReboot/liveOn/View/Gift/VoiceMail/VoicemailPopUpView.swift
  liveOnReboot/liveOn/View/Gift/VoiceMail/VoicemailView.swift
  liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
  liveOnReboot/liveOn/View/GiftList/GiftListView.swift
  liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
  liveOnReboot/liveOn/View/SendGift/SendVoiceMail/SendVoiceMailView.swift
  liveOnReboot/liveOn/ViewModel/Gift/VoiceMail/VoicemailViewModel.swift
  liveOnReboot/liveOnReboot.xcodeproj/project.pbxproj
  liveOnReboot/liveOnReboot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🖇 API, 🧢 Id, 🎤 Voicemail

#74 [Feat] 매칭완료시, 초대코드 화면에서 선물함 뷰로 자동이동
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigEndPoint.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigService.swift
  liveOnReboot/liveOn/View/SignIn/InviteCodeView.swift
  liveOnReboot/liveOn/liveOnRebootApp.swift
Labels: 🖇 API

#85 [Add] 앱 아이콘 수정 & 부와 하투 일러스트 추가
  liveOnReboot/liveOn/Network/Config/APIEnvironment.swift
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/16.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/256.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/32.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/512.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/64.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/Contents.json
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/giftDeliveryFail.imageset/Contents.json
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/giftDeliveryFail.imageset/giftDeliveryFail.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/giftDeliverySuccess.imageset/Contents.json
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/giftDeliverySuccess.imageset/giftDeliverySuccess.png
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/matchSuccess.imageset/Contents.json
  liveOnReboot/liveOn/Resource/Assets.xcassets/hatoo&boo/matchSuccess.imageset/matchSuccess.png
Labels: 😬 teemo, 🎨 Design

#81 [Feat] 사진 선물리스트 뷰 우측 상단 사진 선물 버튼 추가
  liveOnReboot/liveOn/View/Gift/Picture/PictureListView.swift
Labels: 📸 Photo, 🐭 Rookie

#87 [Feat] 꽃 선물하기 및 사진 선물하기 관련 세부 버그사항 수정
  liveOnReboot/.DS_Store
  liveOnReboot/liveOn/Model/Gift/Flower/FlowerModel.swift
  liveOnReboot/liveOn/View/Gift/Flower/FlowerListView.swift
  liveOnReboot/liveOn/View/Gift/Picture/PictureListView.swift
  liveOnReboot/liveOn/View/SendGift/SendFlower/SendFlowerView.swift
  liveOnReboot/liveOn/ViewModel/Gift/Flower/FlowerViewModel.swift
  liveOnReboot/liveOn/liveOnRebootApp.swift
Labels: 💐 Flower, 📸 Photo

#90 [FIX] re-recording btn added & voicemail multiplying solved
  liveOnReboot/liveOn/View/SendGift/SendVoiceMail/SendVoiceMailView.swift
  liveOnReboot/liveOn/ViewModel/Gift/VoiceMail/VoicemailViewModel.swift
Labels: 🧢 Id, 🎤 Voicemail

#102 [Fix] 세세한 사항들 수정
  liveOnReboot/liveOn/Extensions/Color+Extension.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigDTO.swift
  liveOnReboot/liveOn/Network/Auth/Member/MemberConfigService.swift
  liveOnReboot/liveOn/View/CoupleInformation/CoupleInformationView.swift
  liveOnReboot/liveOn/View/CoupleInformation/SettingView.swift
  liveOnReboot/liveOn/View/CoupleInformation/WithdrawalRequestView.swift
  liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
  liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
  liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
  liveOnReboot/liveOn/View/SignIn/InviteCodeView.swift
Labels: 🖇 API
